#!/bin/sh

if command -v python3 >/dev/null 2>&1; then
    interp="python3"
elif command -v python >/dev/null 2>&1; then
    interp="python"
else
    echo "python interpreter not found" >&2
    exit 1
fi

scr_dir="$(cd "$(dirname "$0")" && pwd)"
"$interp" "$scr_dir/pysrc/main.py" "$@"
