#!/bin/sh

scr_dir="$(cd "$(dirname "$0")" && pwd)"
pid_file="$scr_dir/pysrc/.pid"

case "$1" in
    reload)
        kill -HUP $(cat $pid_file)
        exit 0
        ;;
    stop)
        if [ -f "$pid_file" ]; then
            kill "$(cat "$pid_file")" && echo "stopped"
            rm -f "$pid_file"
        fi
        exit 0
        ;;
esac

if command -v python3 >/dev/null 2>&1; then
    interp="python3"
elif command -v python >/dev/null 2>&1; then
    interp="python"
else
    echo "python interpreter not found" >&2
    exit 1
fi

"$interp" "$scr_dir/pysrc/main.py" "$@" &
pid=$!
echo $pid > "$scr_dir/pysrc/.pid"
wait $pid
rm -f "$pid_file"
